language: cpp

compiler:
#  - clang
  - gcc
os:
  - linux
dist: trusty
sudo: required

before_install:
  - sudo apt-get update

script: ./build.sh

notifications:
  email: false
  slack:
    rooms:
      - strathclydesmart:So5Q15xFrEAf8NB4lJaD8PNb
    on_success: never
    on_failure: always