language: cpp

compiler:
  - gcc
os:
  - linux
dist: trusty

script: ./build.sh

notifications:
  email: false
  slack:
    rooms:
      - strathclydesmart:So5Q15xFrEAf8NB4lJaD8PNb
    on_success: change
    on_failure: always